### ISSUE TITLE
How to rotate the mesh 

### ISSUE THREAD

**Issue by TruongKhang** [Jmeyer1292/gl_depth_sim#7]
Hello,
I have the mesh created in another coordinate system (e.g. coordinate system of Colmap [here](https://colmap.github.io/format.html#images-txt)).  According to your source code, I need to convert my mesh to your coordinate system. Am I right? Maybe the solution is to change the rotation matrix in this line code, right?:
`sim.add(*mesh_ptr, Eigen::Affine3d::Identity());`

If it isn't, please suggest me a solution. Thank you so much!

Best,

**Comment by marip8** [comment]
@TruongKhang sorry for the very late response on this issue, but we have recently merged pull requests that address this issue. You can either add the mesh with the appropriate transformation relative to the world coordinate system:

https://github.com/Jmeyer1292/gl_depth_sim/blob/41908589a69902ad12ecc49b20e739a73517be8f/include/gl_depth_sim/sim_depth_camera.h#L60

or you can move a previously added mesh to a new location relative to the world coordinate system.

https://github.com/Jmeyer1292/gl_depth_sim/blob/41908589a69902ad12ecc49b20e739a73517be8f/include/gl_depth_sim/sim_depth_camera.h#L66

The assumption here is that there is a single "world" coordinate system, and both the mesh(es) and camera locations are specified by transforms relative to this coordinate system

**Comment by marip8** [comment]
Closing as this was addressed by #4
